name: 🚀 Feature Request
description: Suggest an idea for GoREAL
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🚀
        
        Please search for existing feature requests before creating a new one.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - API Server
        - Dashboard
        - Database
        - Google Sheets Integration
        - Docker Setup
        - Documentation
        - Roblox Integration
        - Analytics/Reporting
        - Authentication/Security
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        Who would benefit from this feature?
        What specific scenario would this address?
        How would this improve the user experience?

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Drag and drop images here or describe the UI/UX changes

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or implementation ideas
      placeholder: |
        - API changes needed
        - Database schema changes
        - Performance considerations
        - Security implications
        - Dependencies required

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be implemented for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the boxes that apply
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have provided a clear problem statement
          required: true
        - label: I have described a specific solution
          required: true
        - label: I am willing to help implement this feature
          required: false
        - label: I am willing to help test this feature
          required: false