# Prometheus Configuration for GoREAL Production Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'goreal-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configuration for all targets
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter - system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # GoREAL API instances
  - job_name: 'goreal-api-1'
    static_configs:
      - targets: ['api-1:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'
    
  - job_name: 'goreal-api-2'
    static_configs:
      - targets: ['api-2:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Streamlit Dashboard
  - job_name: 'goreal-dashboard'
    static_configs:
      - targets: ['dashboard:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Health checks
  - job_name: 'goreal-health'
    static_configs:
      - targets: ['api-1:8000', 'api-2:8000']
    scrape_interval: 10s
    metrics_path: '/health'
    params:
      format: ['prometheus']

# Remote storage configuration (optional)
# remote_write:
#   - url: "https://prometheus-us-central1.grafana.net/api/prom/push"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"